stages:
  - install
  - prepare
  - build
  - deploy

variables:
  GIT_DEPTH: "1"

npm_ci:
  stage: install
  tags:
    - linux
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules

prepare_jest_env:
  stage: prepare
  dependencies: []
  tags:
    - linux
  script:
    - mkdir -p ygopro
    - git clone --depth=1 https://code.moenext.com/nanahira/ygopro-scripts ygopro/script
    - wget https://code.moenext.com/mycard/ygopro-database/-/raw/master/locales/zh-CN/cards.cdb -O ygopro/cards.cdb
  artifacts:
    paths:
      - ygopro

.build_base:
  stage: build
  tags:
    - linux
  dependencies:
    - npm_ci

build:
  extends:
    - .build_base
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

unit-test:
  extends:
    - .build_base
  dependencies:
    - npm_ci
    - prepare_jest_env
  variables:
    YGOPRO_DIR: ygopro
  script:
    - npm run test

deploy_npm:
  stage: deploy
  dependencies:
    - build
  tags:
    - linux
  script:
    - apt update;apt -y install coreutils
    - echo $NPMRC | base64 --decode > ~/.npmrc
    - npm publish . --access public && curl -X PUT "https://registry-direct.npmmirror.com/$(cat package.json | jq '.name' | sed 's/\"//g')/sync?sync_upstream=true" || true
  only:
    - master
